augeas { "bond_interface" :
    context => "/files/etc/network/interfaces",
    changes => [
        "set auto[child::1 = 'bond0']/1 bond0",
        "set iface[. = 'bond0'] bond0",
        "set iface[. = 'bond0']/family inet",
        "set iface[. = 'bond0']/method manual",
        "set iface[. = 'bond0']/bond-slaves 'eth3 eth2'",
        "set iface[. = 'bond0']/bound-mode balance-xor",
        "set iface[. = 'bond0']/bond-miimon 100",
        "set iface[. = 'bond0']/bond-downdelay 200",
        "set iface[. = 'bond0']/bond-updelay 200",
        "set iface[. = 'bond0']/bond-xmit_hash_policy layer3+4",
        "set auto[child::1 = 'vzbr3100']/1 vzbr3100",
        "set iface[. = 'vzbr3100'] vzbr3100",
        "set iface[. = 'vzbr3100']/family inet",
        "set iface[. = 'vzbr3100']/method static",
        "set iface[. = 'vzbr3100']/bridge_ports bond0.3100",
        "set iface[. = 'vzbr3100']/bridge_maxwait 0",
        "set iface[. = 'vzbr3100']/bridge_fd 0",
        "set iface[. = 'vzbr3100']/address 172.143.115.37",
        "set iface[. = 'vzbr3100']/netmask 255.255.255.224",
        "set auto[child::1 = 'eth4']/1 eth4",
        "set iface[. = 'eth4'] eth4",
        "set iface[. = 'eth4']/family inet",
        "set iface[. = 'eth4']/method static",
        "set iface[. = 'eth4']/address 172.16.0.202",
        "set iface[. = 'eth4']/netmask 255.255.255.0",
    ],
}
